from . import shoppingfeed_channel
from . import shoppingfeed_channel_country_carrier
from . import shoppingfeed_store_order_type_map
from . import shoppingfeed_store_carrier_map
from . import shoppingfeed_store_attribute_field
from . import shoppingfeed_store
from . import shoppingfeed_log
from . import product_template
from . import product_pricelist
from . import stock_quant
from . import sale_order
from . import stock_picking
from . import shoppingfeed_ticket
from . import account_move
from . import product_attribute
